"""add company about column and peer_comparisons table

Revision ID: 3e1d908c68ee
Revises: b53c7ca81285
Create Date: 2026-09-05 22:36:24.250249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1d908c68ee'
down_revision: Union[str, None] = 'b53c7ca81285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peer_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('peer_symbol', sa.String(length=32), nullable=False),
    sa.Column('peer_name', sa.String(length=256), nullable=False),
    sa.Column('is_target', sa.Boolean(), nullable=False),
    sa.Column('cmp', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('pe', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('div_yield', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('net_profit_qtr', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('qtr_profit_var_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sales_qtr', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('qtr_sales_var_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roce_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('source_tier', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'peer_symbol', 'as_of', name='uq_peer_comparison')
    )
    op.add_column('companies', sa.Column('about', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'about')
    op.drop_table('peer_comparisons')
    # ### end Alembic commands ###
