// Drafted to reflect what this product actually is (free, open-source, no
// paid tier, BYO AI key, not a licensed advisory service) — a starting
// point, not a finished legal document. Have it reviewed by a real lawyer
// for your jurisdiction before treating it as final.

import type { Metadata } from 'next';
import { LegalPageLayout } from '@/components/landing/LegalPageLayout';
import styles from '@/components/landing/LegalPageLayout.module.css';

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description: 'The terms for using MarketMitra, hosted or self-hosted.',
};

export default function TermsPage() {
  return (
    <LegalPageLayout eyebrow="Legal" title="Terms & Conditions" updated="12 September 2026">
      <p className={styles.notice}>
        MarketMitra is free and open-source (MIT licensed) with no paid tier, no trial, and no
        subscription — hosted and self-hosted both run the same code under the same terms.
      </p>

      <h2>1. Not investment advice</h2>
      <p>MarketMitra is a data and synthesis tool, not a licensed investment adviser or broker.
      Nothing generated by the dashboard, the AI insights, Mitra chat, research briefs, or the
      multi-agent analysis feature is a recommendation to buy, sell, or hold any security, and none
      of it should be treated as personalised financial advice. Every AI-generated response in this
      product ends with a statement to this effect by design — that isn&apos;t boilerplate we
      forgot to remove, it&apos;s the actual guardrail the product enforces.</p>

      <h2>2. No warranty</h2>
      <p>MarketMitra is provided <strong>&ldquo;as is,&rdquo;</strong> without warranty of any
      kind, express or implied — see the <a href="https://github.com/AnkushGitRepo/marketmitra/blob/main/LICENSE" target="_blank" rel="noreferrer">MIT License</a>{' '}
      for the exact terms. Market data, financial figures, IPO grey-market premiums, and
      AI-generated text may be delayed, incomplete, or wrong. Grey-market premium figures
      specifically are an unofficial third-party estimate, not a verified data point. Verify
      anything material to a financial decision independently before acting on it.</p>

      <h2>3. Bring-your-own AI key</h2>
      <p>AI-powered features require your own API key from a supported provider (Google Gemini,
      Anthropic, or OpenRouter). You are responsible for that provider&apos;s own terms, costs, and
      usage limits — MarketMitra does not bill you for AI usage and has no visibility into or
      control over your provider account.</p>

      <h2>4. Your account and data (hosted deployment)</h2>
      <p>If you use the hosted deployment, you&apos;re responsible for keeping your account
      credentials (managed by Clerk) secure, and for the accuracy of any holdings or alert data
      you enter. Fair-use rate limits apply to the hosted instance to keep it usable for everyone;
      self-hosted instances are not subject to them.</p>

      <h2>5. Self-hosting</h2>
      <p>You may run your own instance of MarketMitra under the MIT License, including for
      commercial purposes, with no obligation to us beyond the license&apos;s attribution
      requirement. You are solely responsible for your own deployment&apos;s security,
      infrastructure, HTTPS/TLS setup, and any third-party services (database, AI provider, email)
      you configure it against.</p>

      <h2>6. Acceptable use</h2>
      <p>Don&apos;t use MarketMitra to violate any applicable law, to attempt to disrupt the
      hosted deployment&apos;s availability for other users, or to circumvent its fair-use rate
      limits. Automated scraping of the hosted deployment beyond the documented, rate-limited API
      surface (see <code>/docs/api-surface.md</code> in the repository) isn&apos;t permitted.</p>

      <h2>7. Changes</h2>
      <p>We may update these terms as the product changes. Continued use of the hosted deployment
      after a material change constitutes acceptance of the updated terms.</p>

      <h2>8. Contact</h2>
      <p>Questions about these terms can be raised via an issue on our{' '}
      <a href="https://github.com/AnkushGitRepo/marketmitra" target="_blank" rel="noreferrer">GitHub repository</a>.</p>
    </LegalPageLayout>
  );
}
